/*
    executor.h - Header file for the command executor component of the shell
    This file declares the functions responsible for executing the AST generated by the parser.
    It includes functions for executing individual commands, pipelines, logical operators, and sequences.
    The main entry point is the `execute` function, which dispatches to the appropriate execution function based on the type of AST node.
*/
#ifndef _EXECUTOR_H_
#define _EXECUTOR_H_

int execute(Node *ast);               // Main entry point for executing the AST
int execute_cmd(Node *node);          // Executes a command node
int execute_pipeline(Node *node);     // Executes a pipeline of commands
int execute_and_or(Node *node);       // Executes logical AND (&&) and OR (||) nodes
int execute_sequence(Node *node);     // Executes a sequence of commands separated by semicolons

#endif
