/*
    executor.h - Header file for the command executor component of the shell
    This file declares the functions responsible for executing the AST generated by the parser.
    It includes functions for executing individual commands, pipelines, logical operators, and sequences.
    The main entry point is the `execute` function, which dispatches to the appropriate execution function based on the type of AST node.
*/
#ifndef EXECUTOR_H
#define EXECUTOR_H

#define HSH_LIST_SIZE 4

/*
    Executes the abstract syntax tree representing a command or a sequence of commands.
    It dispatches to specific execution functions based on the type of AST node (e.g., command, pipeline, AND/OR, sequence).
    Returns the exit status of the executed command(s) or -1 on error.
*/
int execute(Node *ast);               // Main entry point for executing the AST

#endif
